{
    'name': 'Hospital Management',
    'version': '18.0.1.0.0',
    'summary': 'Manage patients, appointments and hospital operations',
    'author': 'Banastech Private Limited',
    'website': 'https://www.banastech.com/',
    'category': 'Healthcare',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'mail',
        'website',
    ],
    "images": [
        'static/description/cover.png',
        'static/description/icon.png',
        'static/img/loan-overview.png',
        'static/img/installment-schedule.png',
        'static/img/payment-tracking.png',
        'static/img/loan-calculator.png',
        'static/img/loan-creation.png',
        'static/img/loan-workflow.png',
        'static/img/repayment-invoices.png',
        'static/img/configurations.png',
        'static/img/vehicle-manufacturers.png',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'views/patient.xml',
        'views/appointment.xml',
        'views/menu.xml',
        'views/template.xml',
    ],
    'installable': True,
    'application': True,
}
